document.writeln("<footer>");
document.writeln("	<div class=\"container\">");
document.writeln("		<div class=\"units-row\">");
document.writeln("			<div class=\"unit-50\">");
document.writeln("				<p>『书摘。』好句摘录<br>Copyright &copy; ");
document.writeln("			    <script>document.write(new Date().getFullYear());</script> <a href=\"https://fly6022.fun/\" target=\"_blank\">fly6022</a> All rights reserved.</p>");
document.writeln("			</div>");
document.writeln("			<div class=\"unit-50\">");
document.writeln("				<ul class=\"social list-flat right\">");
document.writeln("					<li><a href=\"mailto://fly6022@qq.com\" title=\"E-mail\"><i class=\"fa fa-send-o\"></i></a></li>");
document.writeln("					<li><a href=\"https://github.com/https://github.com/Book-Excerpts\" title=\"Github\"><i class=\"fa fa-github-alt\"></i></a></li>");
document.writeln("					<li><a href=\"https://fly6022.fun/\" title=\"Blog\"><i class=\"fa fa-google-plus-square\"></i></a></li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</footer>");
document.write ('<script type="text/javascript"  src="https://js.users.51.la/20302875.js"></script>');