document.writeln("<footer>");
document.writeln("	<div class=\"container\">");
document.writeln("		<div class=\"units-row\">");
document.writeln("			<div class=\"unit-100\">");
document.writeln("				<p>『书摘。』好句摘录<br>Copyright &copy; ");
document.writeln("			    <script>document.write(new Date().getFullYear());</script> <a href=\"https://fly6022.fun/\" target=\"_blank\">fly6022</a> All rights reserved. <br>『书摘。』好句插件开源于 <a href=\"https://github.com/Book-Excerpts/haoju\" target=\"_blank\">Github</a> ，遵循 <a href=\"https://github.com/Book-Excerpts/haoju/blob/master/LICENSE\" target=\"_blank\">MIT</a> 协议.</p>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</footer>");
document.write ('<script type="text/javascript"  src="https://js.users.51.la/20302875.js"></script>');