document.writeln("		<header class=\"group top-nav\">");
document.writeln("			<div class=\"navigation-toggle\" data-tools=\"navigation-toggle\" data-target=\"#navbar-1\">");
document.writeln("				<span class=\"logo\">『书摘。』</span>");
document.writeln("			</div>");
document.writeln("			<nav id=\"navbar-1\" class=\"navbar item-nav\">");
document.writeln("				<ul>");
document.writeln("					<li class=\"active\"><a href=\"index.html\">『书摘。』</a></li>");
document.writeln("					<li><a href=\"haoju.html\">好句</a></li>");
document.writeln("					<li><a href=\"haoduan.html\">好段</a></li>");
document.writeln("					<li><a href=\"donate.html\">捐赠</a></li>");
document.writeln("					<li><a href=\"link.html\">调用</a></li>");
document.writeln("				</ul>");
document.writeln("			</nav>");
document.writeln("		</header>");